Implement RFC 2940
EventStore/Automations pull request #49
Opened 2022-01-31 12:29 UTC by thefringeninja

2022-01-31 16:09 UTC, thefringeninja commented
```
The following tags will be applied:
22.6.0-buster-slim => 22
21.10.1-buster-slim => 21
21.10.1-focal => latest
21.10.1-focal => lts
20.10.5-focal => previous-lts
```

2022-02-02 09:56 UTC, hayley-jean requested changes
I'd just like the readme to be updated, otherwise it looks good to me

2022-02-02 09:56 UTC, hayley-jean commented on tag-docker-images/README.md
> +# Create a JavaScript Action using TypeScript
Could you update the readme to give an overview of the action and what it does?

2022-02-03 10:41 UTC, hayley-jean approved these changes

2022-02-04 12:02 UTC, YoEight approved these changes

2022-02-04 12:03 UTC, merged